CREATE TABLE IF NOT EXISTS MOVIES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    MINUTES INT NOT NULL,
    GENRE VARCHAR(50) NOT NULL,
    DIRECTOR VARCHAR(50) NOT NULL
);

INSERT INTO MOVIES (NAME, MINUTES, GENRE, DIRECTOR) VALUES 
    ('Dark Knight', 152, 'ACTION', 'Christopher Nolan'),
    ('Memento', 113, 'THRILLER', 'Christopher Nolan'),
    ('Matrix', 136, 'ACTION', 'Lilly Wachowski');