CREATE TABLE IF NOT EXISTS MOVIES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    MINUTES INT NOT NULL,
    GENRE VARCHAR(50) NOT NULL
);

INSERT INTO MOVIES (NAME, MINUTES, GENRE) VALUES 
    ('Dark Knight', 152, 'ACTION'),
    ('Memento', 113, 'THRILLER'),
    ('Matrix', 136, 'ACTION');